var COMPODOC_SEARCH_INDEX = {
  index: {
    version: '2.3.9',
    fields: ['title', 'body'],
    fieldVectors: [
      ['title/coverage.html', [0, 1.263]],
      [
        'body/coverage.html',
        [
          0,
          1.191,
          1,
          1.886,
          2,
          1.886,
          3,
          1.191,
          4,
          1.886,
          5,
          1.886,
          6,
          1.886,
          7,
          1.886,
          8,
          1.886,
          9,
          0.118,
          10,
          0.146,
          11,
          0.146,
          12,
          0.118,
        ],
      ],
      ['title/dependencies.html', [13, 1.258, 14, 1.125]],
      [
        'body/dependencies.html',
        [
          9,
          0.061,
          10,
          0.093,
          11,
          0.176,
          12,
          0.061,
          14,
          0.618,
          15,
          0.978,
          16,
          2.469,
          17,
          0.978,
          18,
          1.482,
          19,
          0.978,
          20,
          0.978,
          21,
          0.978,
          22,
          0.978,
          23,
          0.978,
          24,
          0.978,
          25,
          1.482,
          26,
          1.482,
          27,
          0.978,
          28,
          0.978,
          29,
          0.978,
          30,
          0.978,
          31,
          0.978,
          32,
          0.978,
          33,
          0.978,
          34,
          1.482,
          35,
          0.978,
          36,
          1.994,
          37,
          0.978,
          38,
          0.978,
          39,
          0.978,
          40,
          0.978,
          41,
          0.978,
          42,
          0.978,
          43,
          0.978,
          44,
          0.978,
          45,
          0.978,
          46,
          0.978,
          47,
          0.978,
          48,
          0.978,
          49,
          0.618,
          50,
          0.978,
          51,
          0.978,
          52,
          0.978,
          53,
          0.978,
          54,
          0.978,
          55,
          0.978,
          56,
          0.978,
        ],
      ],
      ['title/index.html', [57, 1.258, 58, 1.258, 59, 1.258]],
      [
        'body/index.html',
        [
          3,
          0.571,
          9,
          0.057,
          10,
          0.088,
          11,
          0.088,
          12,
          0.057,
          49,
          0.571,
          60,
          1.396,
          61,
          2.278,
          62,
          0.905,
          63,
          0.905,
          64,
          0.905,
          65,
          1.396,
          66,
          1.396,
          67,
          0.905,
          68,
          0.905,
          69,
          1.704,
          70,
          0.905,
          71,
          0.905,
          72,
          0.905,
          73,
          0.905,
          74,
          0.905,
          75,
          0.905,
          76,
          0.905,
          77,
          0.905,
          78,
          1.704,
          79,
          1.915,
          80,
          2.069,
          81,
          0.905,
          82,
          0.905,
          83,
          1.704,
          84,
          0.905,
          85,
          1.396,
          86,
          1.396,
          87,
          0.905,
          88,
          0.905,
          89,
          1.396,
          90,
          0.905,
          91,
          0.905,
          92,
          1.396,
          93,
          0.905,
          94,
          0.905,
          95,
          2.547,
          96,
          1.396,
          97,
          0.905,
          98,
          1.396,
          99,
          0.905,
          100,
          0.905,
          101,
          0.905,
          102,
          2.186,
          103,
          0.905,
          104,
          0.905,
          105,
          0.905,
        ],
      ],
      ['title/modules.html', [106, 1.263]],
      ['body/modules.html', [9, 0.132, 10, 0.156, 11, 0.156, 12, 0.132, 106, 1.33]],
      ['title/overview.html', [107, 1.263]],
      ['body/overview.html', [9, 0.132, 10, 0.156, 11, 0.156, 12, 0.132, 107, 1.33]],
    ],
    invertedIndex: [
      [
        '',
        {
          _index: 11,
          title: {},
          body: {
            'coverage.html': {},
            'dependencies.html': {},
            'index.html': {},
            'modules.html': {},
            'overview.html': {},
          },
        },
      ],
      ['0.10.3', { _index: 56, title: {}, body: { 'dependencies.html': {} } }],
      ['1+2+3', { _index: 74, title: {}, body: { 'index.html': {} } }],
      ['1.1.4', { _index: 31, title: {}, body: { 'dependencies.html': {} } }],
      ['1.3.0', { _index: 50, title: {}, body: { 'dependencies.html': {} } }],
      ['10.0.14', { _index: 16, title: {}, body: { 'dependencies.html': {} } }],
      ['10.2.7', { _index: 18, title: {}, body: { 'dependencies.html': {} } }],
      ['13.0.0', { _index: 38, title: {}, body: { 'dependencies.html': {} } }],
      ['2.0.0', { _index: 54, title: {}, body: { 'dependencies.html': {} } }],
      ['2.2.2', { _index: 47, title: {}, body: { 'dependencies.html': {} } }],
      ['4', { _index: 75, title: {}, body: { 'index.html': {} } }],
      ['4.0.1', { _index: 44, title: {}, body: { 'dependencies.html': {} } }],
      ['4.5.0', { _index: 45, title: {}, body: { 'dependencies.html': {} } }],
      ['6.0.0', { _index: 41, title: {}, body: { 'dependencies.html': {} } }],
      ['6.5.5', { _index: 52, title: {}, body: { 'dependencies.html': {} } }],
      ['8.0.1', { _index: 35, title: {}, body: { 'dependencies.html': {} } }],
      ['accepts', { _index: 67, title: {}, body: { 'index.html': {} } }],
      ['angular/animations', { _index: 15, title: {}, body: { 'dependencies.html': {} } }],
      ['angular/cdk', { _index: 17, title: {}, body: { 'dependencies.html': {} } }],
      ['angular/common', { _index: 19, title: {}, body: { 'dependencies.html': {} } }],
      ['angular/compiler', { _index: 20, title: {}, body: { 'dependencies.html': {} } }],
      ['angular/core', { _index: 21, title: {}, body: { 'dependencies.html': {} } }],
      ['angular/forms', { _index: 22, title: {}, body: { 'dependencies.html': {} } }],
      ['angular/localize', { _index: 23, title: {}, body: { 'dependencies.html': {} } }],
      ['angular/material', { _index: 24, title: {}, body: { 'dependencies.html': {} } }],
      ['angular/platform', { _index: 25, title: {}, body: { 'dependencies.html': {} } }],
      ['angular/router', { _index: 28, title: {}, body: { 'dependencies.html': {} } }],
      ['application', { _index: 61, title: {}, body: { 'index.html': {} } }],
      ['before', { _index: 89, title: {}, body: { 'index.html': {} } }],
      ['blocks', { _index: 88, title: {}, body: { 'index.html': {} } }],
      ['bootstrap', { _index: 34, title: {}, body: { 'dependencies.html': {} } }],
      ['bootstrap/ng', { _index: 33, title: {}, body: { 'dependencies.html': {} } }],
      ['browser', { _index: 26, title: {}, body: { 'dependencies.html': {} } }],
      ['building', { _index: 87, title: {}, body: { 'index.html': {} } }],
      ['chips', { _index: 46, title: {}, body: { 'dependencies.html': {} } }],
      ['comment', { _index: 66, title: {}, body: { 'index.html': {} } }],
      ['comments', { _index: 60, title: {}, body: { 'index.html': {} } }],
      ['commit', { _index: 90, title: {}, body: { 'index.html': {} } }],
      ['components', { _index: 86, title: {}, body: { 'index.html': {} } }],
      ['confidence', { _index: 81, title: {}, body: { 'index.html': {} } }],
      ['coverage', { _index: 0, title: { 'coverage.html': {} }, body: { 'coverage.html': {} } }],
      ['crud', { _index: 63, title: {}, body: { 'index.html': {} } }],
      ['deep', { _index: 43, title: {}, body: { 'dependencies.html': {} } }],
      ['dependencies', { _index: 14, title: { 'dependencies.html': {} }, body: { 'dependencies.html': {} } }],
      ['displaying', { _index: 62, title: {}, body: { 'index.html': {} } }],
      ['documentation', { _index: 1, title: {}, body: { 'coverage.html': {} } }],
      ['dynamic', { _index: 27, title: {}, body: { 'dependencies.html': {} } }],
      ['e2e', { _index: 79, title: {}, body: { 'index.html': {} } }],
      ['editor', { _index: 30, title: {}, body: { 'dependencies.html': {} } }],
      ['error', { _index: 48, title: {}, body: { 'dependencies.html': {} } }],
      ['expressions', { _index: 72, title: {}, body: { 'index.html': {} } }],
      ['file', { _index: 2, title: {}, body: { 'coverage.html': {} } }],
      ['files', { _index: 91, title: {}, body: { 'index.html': {} } }],
      ['filtering', { _index: 64, title: {}, body: { 'index.html': {} } }],
      ['getting', { _index: 57, title: { 'index.html': {} }, body: {} }],
      ['html', { _index: 70, title: {}, body: { 'index.html': {} } }],
      ['identifier', { _index: 4, title: {}, body: { 'coverage.html': {} } }],
      ['important', { _index: 94, title: {}, body: { 'index.html': {} } }],
      ['index', { _index: 59, title: { 'index.html': {} }, body: {} }],
      ['inside', { _index: 76, title: {}, body: { 'index.html': {} } }],
      ['json', { _index: 100, title: {}, body: { 'index.html': {} } }],
      ['kolkov/angular', { _index: 29, title: {}, body: { 'dependencies.html': {} } }],
      ['lint', { _index: 104, title: {}, body: { 'index.html': {} } }],
      ['linter', { _index: 92, title: {}, body: { 'index.html': {} } }],
      ['loader', { _index: 40, title: {}, body: { 'dependencies.html': {} } }],
      ['look', { _index: 84, title: {}, body: { 'index.html': {} } }],
      [
        'matching',
        {
          _index: 10,
          title: {},
          body: {
            'coverage.html': {},
            'dependencies.html': {},
            'index.html': {},
            'modules.html': {},
            'overview.html': {},
          },
        },
      ],
      ['math', { _index: 71, title: {}, body: { 'index.html': {} } }],
      ['message', { _index: 49, title: {}, body: { 'dependencies.html': {}, 'index.html': {} } }],
      ['mock', { _index: 99, title: {}, body: { 'index.html': {} } }],
      ['mock:server', { _index: 103, title: {}, body: { 'index.html': {} } }],
      ['modules', { _index: 106, title: { 'modules.html': {} }, body: { 'modules.html': {} } }],
      ['need', { _index: 97, title: {}, body: { 'index.html': {} } }],
      ['new', { _index: 6, title: {}, body: { 'coverage.html': {} } }],
      ['ng', { _index: 32, title: {}, body: { 'dependencies.html': {} } }],
      ['ngx', { _index: 36, title: {}, body: { 'dependencies.html': {} } }],
      ['npm', { _index: 102, title: {}, body: { 'index.html': {} } }],
      ['overview', { _index: 107, title: { 'overview.html': {} }, body: { 'overview.html': {} } }],
      ['package', { _index: 13, title: { 'dependencies.html': {} }, body: {} }],
      ['renders', { _index: 68, title: {}, body: { 'index.html': {} } }],
      [
        'result',
        {
          _index: 9,
          title: {},
          body: {
            'coverage.html': {},
            'dependencies.html': {},
            'index.html': {},
            'modules.html': {},
            'overview.html': {},
          },
        },
      ],
      [
        'results',
        {
          _index: 12,
          title: {},
          body: {
            'coverage.html': {},
            'dependencies.html': {},
            'index.html': {},
            'modules.html': {},
            'overview.html': {},
          },
        },
      ],
      ['run', { _index: 95, title: {}, body: { 'index.html': {} } }],
      ['runns', { _index: 93, title: {}, body: { 'index.html': {} } }],
      ['rxjs', { _index: 51, title: {}, body: { 'dependencies.html': {} } }],
      ['see', { _index: 105, title: {}, body: { 'index.html': {} } }],
      ['serve', { _index: 96, title: {}, body: { 'index.html': {} } }],
      ['server', { _index: 101, title: {}, body: { 'index.html': {} } }],
      ['simple', { _index: 69, title: {}, body: { 'index.html': {} } }],
      ['start', { _index: 98, title: {}, body: { 'index.html': {} } }],
      ['started', { _index: 58, title: { 'index.html': {} }, body: {} }],
      ['statements', { _index: 5, title: {}, body: { 'coverage.html': {} } }],
      ['storybook', { _index: 83, title: {}, body: { 'index.html': {} } }],
      ['table', { _index: 8, title: {}, body: { 'coverage.html': {} } }],
      ["tablesort(document.getelementbyid('coverage", { _index: 7, title: {}, body: { 'coverage.html': {} } }],
      ['tags', { _index: 65, title: {}, body: { 'index.html': {} } }],
      ['test', { _index: 85, title: {}, body: { 'index.html': {} } }],
      ['tests', { _index: 80, title: {}, body: { 'index.html': {} } }],
      ['translate/core', { _index: 37, title: {}, body: { 'dependencies.html': {} } }],
      ['translate/http', { _index: 39, title: {}, body: { 'dependencies.html': {} } }],
      ['try', { _index: 73, title: {}, body: { 'index.html': {} } }],
      ['tslib', { _index: 53, title: {}, body: { 'dependencies.html': {} } }],
      ['type', { _index: 3, title: {}, body: { 'coverage.html': {}, 'index.html': {} } }],
      ['types/clone', { _index: 42, title: {}, body: { 'dependencies.html': {} } }],
      ['unit', { _index: 78, title: {}, body: { 'index.html': {} } }],
      ['working', { _index: 82, title: {}, body: { 'index.html': {} } }],
      ['written', { _index: 77, title: {}, body: { 'index.html': {} } }],
      ['zone.js', { _index: 55, title: {}, body: { 'dependencies.html': {} } }],
    ],
    pipeline: ['stemmer'],
  },
  store: {
    'coverage.html': {
      url: 'coverage.html',
      title: 'coverage - coverage',
      body:
        '\n                   \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                   \n\n\n\n    Documentation coverage\n\n\n\n    \n\n\n\n    \n        \n            File\n            Type\n            Identifier\n            Statements\n        \n    \n    \n    \n\n\n\n\n\n    new Tablesort(document.getElementById(\'coverage-table\'));\n\n\n                   \n    \n         result-matching ""\n        \n    \n    \n        No results matching ""\n    \n\n',
    },
    'dependencies.html': {
      url: 'dependencies.html',
      title: 'package-dependencies - dependencies',
      body:
        '\n                   \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n    \n        Dependencies\n    \n    \n        \n            @angular/animations : ~10.0.14\n        \n            @angular/cdk : ^10.2.7\n        \n            @angular/common : ~10.0.14\n        \n            @angular/compiler : ~10.0.14\n        \n            @angular/core : ~10.0.14\n        \n            @angular/forms : ~10.0.14\n        \n            @angular/localize : ~10.0.14\n        \n            @angular/material : ^10.2.7\n        \n            @angular/platform-browser : ~10.0.14\n        \n            @angular/platform-browser-dynamic : ~10.0.14\n        \n            @angular/router : ~10.0.14\n        \n            @kolkov/angular-editor : ^1.1.4\n        \n            @ng-bootstrap/ng-bootstrap : ^8.0.1\n        \n            @ngx-translate/core : ^13.0.0\n        \n            @ngx-translate/http-loader : ^6.0.0\n        \n            @types/clone-deep : ^4.0.1\n        \n            bootstrap : ^4.5.0\n        \n            ngx-chips : ^2.2.2\n        \n            ngx-error-message : ^1.3.0\n        \n            rxjs : ~6.5.5\n        \n            tslib : ^2.0.0\n        \n            zone.js : ~0.10.3\n    \n\n                   \n\n\n\n\n                   \n    \n         result-matching ""\n        \n    \n    \n        No results matching ""\n    \n\n',
    },
    'index.html': {
      url: 'index.html',
      title: 'getting-started - index',
      body:
        '\n                   \n\nComments Application\nThere is an application for displaying comments (with CRUD) and filtering by tags.\nComment message accepts and renders simple html tags, and also simple math expressions try to type:\n1+2+3-4 inside comment.\nAlso I have written unit and e2e tests, to have a confidence that application is working.\nThis application has storybook to look at and test the simple components (building blocks) of application.\nBefore commit files the linter and unit tests runns.\n!important!\nBefore you run e2e tests or serve the application you need start mock json server:\nnpm run mock:server\nServe application\nnpm run start\nTo run linter\nnpm run lint\nTo run unit tests\nnpm run test\nTo run e2e tests\nnpm run e2e\nTo run storybook and see your components run\nnpm run storybook\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                   \n\n\n\n\n                   \n    \n         result-matching ""\n        \n    \n    \n        No results matching ""\n    \n\n',
    },
    'modules.html': {
      url: 'modules.html',
      title: 'modules - modules',
      body:
        '\n                   \n\n\n\n\n    Modules\n\n\n    \n    \n\n\n\n\n\n\n\n\n\n\n\n\n                   \n\n\n\n\n                   \n    \n         result-matching ""\n        \n    \n    \n        No results matching ""\n    \n\n',
    },
    'overview.html': {
      url: 'overview.html',
      title: 'overview - overview',
      body:
        '\n                   \n\n\n\n    Overview\n\n    \n\n    \n    \n\n\n \n\n\n\n\n\n\n\n\n\n\n\n                   \n\n\n\n\n                   \n    \n         result-matching ""\n        \n    \n    \n        No results matching ""\n    \n\n',
    },
  },
};
